.TH "" "" "" "" ""
.SH wordspread [IMAGE: NPM
version (https://badge.fury.io/js/wordspread.svg)] (http://badge.fury.io/js/wordspread)
.SS Install globally with npm (npmjs.org):
.IP
.nf
\f[C]
npm\ i\ \-g\ wordspread
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ wordspread\ LINK\ TITLE\ [\ \-n\ |\ \-\-no\-show\-hn\ ]\ [\ \-s\ SUB\ |\ \-\-subreddit\ SUB\ ]
\ \ \ \ wordspread\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ wordspread
\ \ \ \ \-n,\ \-\-no\-show\-hn\ \ \ \ \ \ \ \ dont\ prefix\ posts\ on\ HN\ with\ \[aq]Show\ HN:\[aq]
\ \ \ \ \-s,\ \-\-subreddit\ SUB\ \ \ \ \ specify\ subreddit

Arguments:
\ \ \ \ LINK\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ url\ of\ the\ link\ to\ publish
\ \ \ \ TITLE\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ title\ of\ the\ post.
\f[]
.fi
.SS What is it
.PP
Creates submission links for Reddit and HN
.PP
Example:
.IP
.nf
\f[C]
>\ wordspread\ \[aq]https://github.com/petkaantonov/bluebird\[aq]\ \[aq]Bluebird\[aq]

Use\ (⌘\ +double\ click)\ to\ open\ links\ on\ OSX
wordspread\ HN:\ \ https://news.ycombinator.com/submitlink?u=https%3A%2F%2Fgithub.com%2Fpetkaantonov%2Fbluebird&t=Show+HN%3A+Bluebird
wordspread\ Reddit\ /r/javascript:\ \ http://www.reddit.com/submit?url=https%3A%2F%2Fgithub.com%2Fpetkaantonov%2Fbluebird&title=Bluebird&sr=javascript
\f[]
.fi
.SS To do
.IP \[bu] 2
Post on twitter
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Copyright (c) 2015 Vittorio Zaccaria Released under the BSD License.
.PP
   *   *   *   *   *
.PP
\f[I]This file was generated by
verb\-cli (https://github.com/assemble/verb-cli) on April 23, 2015.\f[]
